import fs from 'fs';
import path from 'path';

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

function makeShadowString(shadows: any[]) {
  return shadows
    .map((s) => {
      const x = s.x + 'px';
      const y = s.y + 'px';
      const blur = s.blur + 'px';
      const spread = s.spread + 'px';
      const color = s.color;
      return `${x} ${y} ${blur} ${spread} ${color}`;
    })
    .join(', ');
}

const raw = loadJSON('tokens/tokens.json');

// 최상위에 이미 완전히 해석된 shadow 정의들이 있음
const topLevel = raw[''] ?? {};

const shadowKeys = Object.keys(topLevel).filter((key) => topLevel[key]?.type === 'boxShadow');

if (shadowKeys.length === 0) {
  console.warn('⚠️  No shadow tokens found in root level');
}

// 실사용 CSS 파일 경로
const outPath = path.resolve('src/shared/styles/shadow-tokens.css');

// 출력 디렉터리 보장
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-shadow.ts */\n@theme {\n`;

for (const key of shadowKeys) {
  const shadowDef = topLevel[key];
  if (!shadowDef) {
    console.warn(`⚠️  Shadow key "${key}" not found in root level`);
    continue;
  }

  // value가 배열이면 그대로, 단일 객체면 배열로 감싸기
  const shadowArray = Array.isArray(shadowDef.value) ? shadowDef.value : [shadowDef.value];

  const cssShadow = makeShadowString(shadowArray);

  cssOutput += `  --box-shadow-${key}: ${cssShadow};\n`;
}

cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
