import fs from 'fs';
import path from 'path';

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

// 원시 토큰 로드
const primitiveLight = loadJSON('tokens/primitive-light.json');
const semanticLight = loadJSON('tokens/semantic-light.json');
const primitiveDark = loadJSON('tokens/primitive-dark.json');
const semanticDark = loadJSON('tokens/semantic-dark.json');

function flatten(obj: any, prefix = '', result: Record<string, any> = {}) {
  if (!obj || typeof obj !== 'object') return result;

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    const newKey = prefix ? `${prefix}.${key}` : key;

    if (value && typeof value === 'object' && '$type' in value) {
      result[newKey] = value;
    } else if (value && typeof value === 'object') {
      flatten(value, newKey, result);
    }
  }
  return result;
}

// primitive 토큰 평탄화
const primitiveMapLight = Object.fromEntries(
  Object.entries(flatten(primitiveLight)).map(([k, v]: [string, any]) => [k, v.$value]),
);
const primitiveMapDark = Object.fromEntries(
  Object.entries(flatten(primitiveDark)).map(([k, v]: [string, any]) => [k, v.$value]),
);

function toCSSVarName(key: string): string {
  return key.replace(/\./g, '-');
}

function resolveSemantics(flattened: Record<string, any>, primitiveMap: Record<string, string>) {
  const resolved: Record<string, string> = {};
  for (const key of Object.keys(flattened)) {
    const token = flattened[key];
    if (token.$type === 'color') {
      let raw = token.$value;
      const match = raw.match(/\{([^}]+)\}/);
      if (match) {
        const ref = match[1];
        raw = primitiveMap[ref] || raw;
      }
      resolved[toCSSVarName(key)] = raw;
    }
  }
  return resolved;
}

// semantic 토큰 - primitive 토큰 연결
const lightColors = resolveSemantics(flatten(semanticLight), primitiveMapLight);
const darkColors = resolveSemantics(flatten(semanticDark), primitiveMapDark);

// 실사용 CSS 파일 경로
const outPath = path.resolve('src/shared/styles/color-tokens.css');

// 출력 디렉터리 보장
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-color.ts */\n@theme {\n`;
Object.entries(lightColors)
  .sort(([a], [b]) => a.localeCompare(b))
  .forEach(([key, value]) => {
    cssOutput += `  --${key}: ${value};\n`;
  });
cssOutput += '}\n\n';

cssOutput += `[data-theme="dark"] {\n`;
Object.entries(darkColors)
  .sort(([a], [b]) => a.localeCompare(b))
  .forEach(([key, value]) => {
    cssOutput += `  --${key}: ${value};\n`;
  });
cssOutput += '}\n';

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
