import fs from 'fs';
import path from 'path';

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

// ref 해석
function resolveRef(root: any, val: any) {
  if (typeof val === 'string') {
    const m = val.match(/^\{([^}]+)\}$/);
    if (m) {
      const ref = m[1];
      const parts = ref.split('.');
      let cur = root;
      for (const p of parts) {
        if (!cur[p]) return val;
        cur = cur[p];
      }
      return 'value' in cur ? cur.value : cur;
    }
  }
  return val;
}

function makeShadowString(shadows: any[]) {
  return shadows
    .map((s) => {
      const x = s.x + 'px';
      const y = s.y + 'px';
      const blur = s.blur + 'px';
      const spread = s.spread + 'px';
      const color = s.color;
      return `${x} ${y} ${blur} ${spread} ${color}`;
    })
    .join(', ');
}

function buildShadowFromSemantic(root: any, semantic: any) {
  const out: any[] = [];

  const get = (key: string) => resolveRef(root, semantic[key]?.value);

  // 공통 normal
  const common = {
    x: Number(get('x-normal') ?? 0),
    blur: Number(get('blur') ?? 0),
    spread: Number(get('spread') ?? 0),
  };

  // normal shadow
  out.push({
    x: common.x,
    y: Number(get('y-normal') ?? 0),
    blur: Number(get('blur') ?? 0),
    spread: common.spread,
    color: String(get('color-normal')),
  });

  // secondary shadow가 존재한다면 추가
  if (semantic['y-secondary']) {
    out.push({
      x: common.x,
      y: Number(get('y-secondary')),
      blur: Number(get('blur-secondary') ?? get('blur')),
      spread: common.spread,
      color: String(get('color-secondary')),
    });
  }

  // tertiary shadow (floated에만 있음)
  if (semantic['y-tertiary']) {
    out.push({
      x: common.x,
      y: Number(get('y-tertiary')),
      blur: Number(get('blur-tertiary')),
      spread: common.spread,
      color: String(get('color-tertiary')),
    });
  }

  return out;
}

//
// MAIN
//
const raw = loadJSON('tokens/tokens.json');

const semanticLight = raw['Semantic/Light']?.effect?.shadow ?? {};

const shadowKeys = [
  'embossed',
  'embossed-inverse',
  'raised',
  'raised-inverse',
  'floated',
  'lifted',
];

// CSS 출력 준비
let css = `/* auto generated by convert-shadow.ts */\n:root {\n`;

// Tailwind preset JS
const tw = {
  boxShadow: {} as Record<string, string>,
};

for (const key of shadowKeys) {
  const sem = semanticLight[key];
  if (!sem) continue;

  const resolved = buildShadowFromSemantic(raw, sem);
  const cssShadow = makeShadowString(resolved);

  css += `  --shadow-${key}: ${cssShadow};\n`;
  tw.boxShadow[key] = `var(--shadow-${key})`;
}

css += `}\n`;

fs.writeFileSync('src/shared/styles/shadow-tokens.css', css, 'utf-8');
fs.writeFileSync(
  'src/shared/styles/shadow-preset.js',
  'module.exports = ' + JSON.stringify(tw, null, 2),
  'utf-8',
);

console.log('✅ shadow tokens + tailwind preset generated');
