import fs from 'fs';
import path from 'path';

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

// 원시 토큰 로드
const raw = loadJSON('tokens/typography.json');
const meta = raw[''] ?? {};
const groups = { Title: meta.Title, Body: meta.Body, Caption: meta.Caption };

const weightMap: Record<string, string | number> = {
  thin: '100',
  extralight: '200',
  light: '300',
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
};

const textCaseMap: Record<string, string> = {
  original: 'none',
  upper: 'uppercase',
  lower: 'lowercase',
  title: 'capitalize',
  none: 'none',
};

// ---------- 유틸들 ----------
function normalizeWeight(str: string) {
  const key = str?.toLowerCase?.();
  return weightMap[key] ?? str; // 숫자 문자열/숫자 유지
}

function ensureDim(val: unknown, fallback = '0px') {
  // 숫자면 px, 문자열이면 px/em/rem/% 등 단위 보존, 비정상이면 fallback
  if (val == null) return fallback;
  if (typeof val === 'number' && Number.isFinite(val)) return `${val}px`;
  if (typeof val === 'string') {
    const v = val.trim();
    if (/^-?\d+(\.\d+)?(px|em|rem|%)$/.test(v)) return v;
    const n = parseFloat(v);
    return Number.isFinite(n) ? `${n}px` : fallback;
  }
  return fallback;
}

function ensureNumberOrRaw(val: unknown) {
  // 여기서는 px로 가되, 문자열 단위가 있으면 그대로.
  if (val == null) return 'normal';
  if (typeof val === 'number' && Number.isFinite(val)) return `${val}px`;
  if (typeof val === 'string') {
    const v = val.trim();
    if (/^-?\d+(\.\d+)?(px|em|rem|%)$/.test(v)) return v;
    const n = parseFloat(v);
    return Number.isFinite(n) ? `${n}px` : 'normal';
  }
  return 'normal';
}

function ensureLetterSpacing(val: unknown) {
  // normal | <length>; percentage는 미허용
  if (val == null) return 'normal';
  if (typeof val === 'number' && Number.isFinite(val)) return `${val}px`;
  if (typeof val === 'string') {
    const v = val.trim().toLowerCase();
    if (v === 'normal') return 'normal';
    if (/^-?\d+(\.\d+)?(px|em|rem)$/.test(v)) return v;
    const n = parseFloat(v);
    return Number.isFinite(n) ? `${n}px` : 'normal';
  }
  return 'normal';
}

function makeClassName(group: string, key: string) {
  return `.text-${group.toLowerCase()}-${key.toLowerCase().replace(/_/g, '-')}`;
}

// 참조 해석 유틸
function resolveRef(obj: any, ref: string) {
  if (!ref) return '';
  const clean = ref.replace(/[{}]/g, '');
  const pathParts = clean.split('.');
  let current = obj;
  for (const part of pathParts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
      if (current && typeof current === 'object' && 'value' in current) {
        current = current.value;
      }
    }
  }
  return current;
}

// 실사용 CSS 파일 경로
const outPath = path.resolve('src/shared/styles/font-tokens.css');

// 출력 디렉터리 보장
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-typo.ts */\n@layer utilities {\n`;

for (const [groupName, groupObj] of Object.entries(groups)) {
  if (!groupObj) continue;

  for (const [key, token] of Object.entries<any>(groupObj)) {
    const val = token.value;
    const className = makeClassName(groupName, key);

    const fontFamily = resolveRef(meta, val.fontFamily) || 'sans-serif';
    const fontWeight = normalizeWeight(resolveRef(meta, val.fontWeight));
    const lineHeightRaw = resolveRef(meta, val.lineHeight);
    const fontSizeRaw = resolveRef(meta, val.fontSize);
    const letterSpacingRaw = resolveRef(meta, val.letterSpacing);
    const paragraphSpacingRaw = resolveRef(meta, val.paragraphSpacing);
    const paragraphIndentRaw = resolveRef(meta, val.paragraphIndent);
    const textCaseRaw = resolveRef(meta, val.textCase);
    const textDecoration = resolveRef(meta, val.textDecoration) || 'none';

    const lineHeight = ensureNumberOrRaw(lineHeightRaw);
    const fontSize = ensureDim(fontSizeRaw); // px로
    const letterSpacing = ensureLetterSpacing(letterSpacingRaw);
    const paragraphSpacing = ensureDim(paragraphSpacingRaw, '0px');
    const paragraphIndent = ensureDim(paragraphIndentRaw, '0px');
    const textTransform = textCaseMap[String(textCaseRaw ?? 'none').toLowerCase()] || 'none';

    cssOutput += `  ${className} {\n`;
    cssOutput += `    font-family: ${fontFamily}, sans-serif;\n`;
    cssOutput += `    font-weight: ${fontWeight};\n`;
    cssOutput += `    line-height: ${lineHeight};\n`;
    cssOutput += `    font-size: ${fontSize};\n`;
    cssOutput += `    letter-spacing: ${letterSpacing};\n`;
    cssOutput += `    text-indent: ${paragraphIndent};\n`;
    cssOutput += `    text-transform: ${textTransform};\n`;
    cssOutput += `    text-decoration: ${textDecoration};\n`;
    cssOutput += `  }\n`;

    // 문단 간격은 실제 문단 요소에 적용
    cssOutput += `  ${className} p { margin-bottom: ${paragraphSpacing}; }\n`;
  }
}

cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
