import fs from 'fs';
import path from 'path';

type Leaf = { value: any; type: string } | Record<string, any>;

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

function get(obj: any, keyPath: string) {
  return keyPath.split('.').reduce<any>((acc, k) => (acc ? acc[k] : undefined), obj);
}

function resolveRef(root: any, val: any): any {
  if (typeof val === 'string') {
    const m = val.match(/^\{([^}]+)\}$/);
    if (m) {
      const ref = m[1]; // e.g. "unit.1-2"
      const node = get(root, ref);
      if (node && typeof node === 'object' && 'value' in node) {
        return resolveRef(root, node.value);
      }
      return node ?? val;
    }
  }
  return val;
}

function flatten(obj: Leaf, prefix = '', out: Record<string, { value: any; type: string }> = {}) {
  if (!obj || typeof obj !== 'object') return out;
  if ('value' in obj && 'type' in obj) {
    out[prefix] = obj as any;
    return out;
  }
  for (const k of Object.keys(obj)) {
    const v = (obj as any)[k];
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object') flatten(v, key, out);
  }
  return out;
}

// 원시 토큰 로드
const raw = loadJSON('tokens/scheme.json');
const scheme = raw['Scheme/Default'];
if (!scheme) throw new Error('"Scheme/Default"가 없습니다.');

// 평탄화 + 참조해석된 숫자 스케일 만들기
function pickResolved(prefix: string) {
  const flat = flatten(scheme);
  const entries = Object.entries(flat).filter(
    ([k, v]) => k.startsWith(prefix + '.') && (v as any).type === 'number',
  );
  const obj: Record<string, number> = {};
  for (const [k, tok] of entries) {
    const name = k.slice(prefix.length + 1); // "1-2"
    const resolved = resolveRef(scheme, (tok as any).value);
    obj[name] = typeof resolved === 'number' ? resolved : parseFloat(String(resolved));
  }
  return obj;
}

const spacingTok = pickResolved('spacing'); // "1".."20"
const radiusTok = pickResolved('radius'); // "1".."7","max"
const strokeTok = pickResolved('stroke.weight'); // "1","2","3","4","5","iconL","iconM","iconS"
const opacityTok = pickResolved('opacity'); // "30","50","100"

// 값 포맷
const spacingPx: Record<string, string> = {};
for (const [k, v] of Object.entries(spacingTok)) spacingPx[k] = `${v}px`;

const radiusPx: Record<string, string> = {};
for (const [k, v] of Object.entries(radiusTok)) radiusPx[k] = `${v}px`;

const strokeVal: Record<string, string> = {};
for (const [k, v] of Object.entries(strokeTok)) strokeVal[k] = `${v}px`;


const opacityVal: Record<string, string> = {};
for (const [k, v] of Object.entries(opacityTok)) opacityVal[k] = (v / 100).toString();

const varSpacing = (k: string) => `--spacing-${k}`;
const varRadius = (k: string) => `--radius-${k}`;
const varStroke = (k: string) => `--stroke-weight-${k}`;
const varOpacity = (k: string) => `--opacity-${k}`;

// 실사용 CSS 파일 경로
const outPath = path.resolve('src/shared/styles/scheme-tokens.css');

// 출력 디렉터리 보장
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-scheme.ts */\n @theme {\n`;
Object.entries(spacingPx)
  .sort()
  .forEach(([k, v]) => (cssOutput += `  ${varSpacing(k)}: ${v};\n`));
Object.entries(radiusPx)
  .sort()
  .forEach(([k, v]) => (cssOutput += `  ${varRadius(k)}: ${v};\n`));
Object.entries(strokeVal)
  .sort()
  .forEach(([k, v]) => (cssOutput += `  ${varStroke(k)}: ${v};\n`));
Object.entries(opacityVal)
  .sort()
  .forEach(([k, v]) => (cssOutput += `  ${varOpacity(k)}: ${v};\n`));
cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);