import fs from 'fs';
import path from 'path';

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(path.resolve(filePath), 'utf-8'));
}

// 원시 토큰 로드
const raw = loadJSON('tokens/typography.json');
const meta = raw[''] ?? {};
const groups = { Head: meta.Head, Body: meta.Body, Caption: meta.Caption };

const weightMap: Record<string, string | number> = {
  thin: '100',
  extralight: '200',
  light: '300',
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
};

function normalizeWeight(str: string) {
  const key = str?.toLowerCase?.();
  return weightMap[key] ?? str;
}

function normalizeLetterSpacing(str: string) {
  if (typeof str === 'string' && str.endsWith('%')) {
    const num = parseFloat(str);
    return `${num / 100}em`;
  }
  return str;
}

function makeClassName(group: string, key: string) {
  return `.text-${group.toLowerCase()}-${key.replace(/_/g, '-')}`;
}

// 참조 해석 유틸
function resolveRef(obj: any, ref: string) {
  if (!ref) return '';
  const clean = ref.replace(/[{}]/g, '');
  const pathParts = clean.split('.');
  let current = obj;
  for (const part of pathParts) {
    if (current && typeof current === 'object' && part in current) {
      current = current[part];
      if (current && typeof current === 'object' && 'value' in current) {
        current = current.value;
      }
    }
  }
  return current;
}

// 실사용 CSS 파일 경로
const outPath = path.resolve('src/shared/styles/font-tokens.css');

// 출력 디렉터리 보장
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/*auto generated by convert-typo.ts*/\n@layer utilities {\n`;
for (const [groupName, groupObj] of Object.entries(groups)) {
  if (!groupObj) continue;

  for (const [key, token] of Object.entries<any>(groupObj)) {
    const val = token.value;
    const className = makeClassName(groupName, key);

    const fontFamily = resolveRef(meta, val.fontFamily) || 'sans-serif';
    const fontWeight = normalizeWeight(resolveRef(meta, val.fontWeight));
    const fontSize = resolveRef(meta, val.fontSize);
    const lineHeight = resolveRef(meta, val.lineHeight);
    const letterSpacing = normalizeLetterSpacing(resolveRef(meta, val.letterSpacing));
    const paragraphSpacing = resolveRef(meta, val.paragraphSpacing);
    const paragraphIndent = resolveRef(meta, val.paragraphIndent);
    const textCase = resolveRef(meta, val.textCase);
    const textDecoration = resolveRef(meta, val.textDecoration);

    cssOutput += `  ${className} {\n`;
    cssOutput += `    font-family: ${fontFamily}, sans-serif;\n`;
    cssOutput += `    font-weight: ${fontWeight};\n`;
    cssOutput += `    line-height: ${lineHeight}px;\n`;
    cssOutput += `    font-size: ${fontSize}px;\n`;
    cssOutput += `    letter-spacing: ${letterSpacing};\n`;
    if (paragraphSpacing && paragraphSpacing !== '0') {
      cssOutput += `    margin-bottom: ${paragraphSpacing}px;\n`;
    }
    if (paragraphIndent && paragraphIndent !== '') {
      cssOutput += `    text-indent: ${paragraphIndent};\n`;
    }
    if (textCase && textCase !== '') {
      cssOutput += `    text-transform: ${textCase};\n`;
    }
    if (textDecoration && textDecoration !== '') {
      cssOutput += `    text-decoration: ${textDecoration};\n`;
    }
    cssOutput += `  }\n`;
  }
}
cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
